### ISSUE TITLE
Problem with Shikanoin Heizou in Character Calculator

### ISSUE THREAD

**Issue by Bagny89** [dvaJi/genshin-builds#10]
In **Character Calculator,** the heizou img is not loaded correctly and there is a repetition of the name.

![Screenshot 2022-07-14 00 24 35](https://user-images.githubusercontent.com/33706352/178847564-082313bf-7c45-432d-93ca-a875cbdd6d69.png)

Also, if you want to calculate how many materials you need to level it, **clicking on "Calculate"** does not show anything.

![Screenshot 2022-07-14 00 29 47](https://user-images.githubusercontent.com/33706352/178848018-b4d34bce-47b9-4570-913b-83bed5cc1cd3.png)

**Comment by dvaJi** [comment]
Thank you for reporting it, it is fixed now.
