### ISSUE TITLE
Runic Fang img not available

### ISSUE THREAD

**Issue by Bagny89** [dvaJi/genshin-builds#11]
**The miniature of Runic Fang is not present.**

![image](https://user-images.githubusercontent.com/33706352/179692635-698c78c5-bee0-47ca-b1c7-43fc73cc9f00.png)

![image](https://user-images.githubusercontent.com/33706352/179692887-a05feec0-2a7d-4ed7-8604-d9282e96327a.png)

**Comment by dvaJi** [comment]
Thank you for reporting it, it is fixed now.
