### ISSUE TITLE
About Vietnamese Language - Translation Contribution.

### ISSUE THREAD

**Issue by kaioken166** [dvaJi/genshin-builds#14]
I love your design of this website and how fast they respond to my interaction.

I'm also a college student in web programming so I very much appreciate your website.
But today I am about using the Vietnamese language on the web, i see some translation errors. I want to contribute to making a more 'perfect' website Genshin-build for everyone. If you see this, I hope you have a look at my contribution.

![image](https://user-images.githubusercontent.com/63769912/211241656-07cd4d53-6ac7-4ea2-bb44-18e84b449db5.png)
Talents Priority -> Ưu tiên Thiên Phú
Artifacts -> Thánh Di Vật
Skill -> Kỹ năng Nguyên tố
Burst -> Kỹ năng Nộ
Normal Attack -> Tấn công thường

Main stat of Artifact:
Sands -> Đồng hồ
Goblet -> Ly
Circlet -> Nón

CRIT Rate / CRIT DMG / ATK% / Energy Recharge / Elemental Mastery / ATK ->
Tỷ lệ Bạo kích / Sát thương bạo kích / ATK% / Hiệu quả nạp nguyên tố / Tinh thông nguyên tố / ATK

![image](https://user-images.githubusercontent.com/63769912/211242647-eb254eaf-3629-4a8d-bffc-929f9ae63fde.png)
Stat -> Chỉ số
Refinement -> Tinh luyện

![image](https://user-images.githubusercontent.com/63769912/211242764-0694a088-9126-4dc5-b2b3-c9ead49d7ea4.png)
Passive Talent -> Thiên phú nội tại
Constellations -> Cung mệnh

Thanks for your effort.

**Comment by dvaJi** [comment]
Thanks, I've added them to the vi.json file!
