### ISSUE TITLE
Imgs on page Alhaitham and Nahida doesn't loading

### ISSUE THREAD

**Issue by Axel0689** [dvaJi/genshin-builds#15]
Images not loading properly on page related to Alhaitham: 😎

![image](https://user-images.githubusercontent.com/33706352/214385272-34082aff-ca78-47b9-b8b7-ef6e1fb61125.png)

Also on Nahida:

![image](https://user-images.githubusercontent.com/33706352/214385773-26f29555-f0f3-4634-8978-e057f5d90329.png)

**Comment by dvaJi** [comment]
I just fixed them, thanks for reporting it!
