### ISSUE TITLE
Tools menu gone (?)

### ISSUE THREAD

**Issue by m33m33** [dvaJi/genshin-builds#16]
Hi,

on https://genshin-builds.com the Tools menu on the top menu bar is gone isn't it ?

Hovering on the menu don't open slide down list, clicking on Tools menu is not possible (not clickable/no link).

As far as I remember, the Tools menu used to actually show new content and tools, right ?

(In the process of cloning/building on my local machine to give it a try here)

Bye

**Comment by m33m33** [comment]
Not much success with npm and yarn :/

```
# npm run dev

> genshin-builds@0.1.0 dev /raid/home/ml/src/genshin-builds
> next dev

sh: 1: next: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! genshin-builds@0.1.0 dev: `next dev`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the genshin-builds@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ml/.npm/_logs/2023-01-28T07_59_59_256Z-debug.log


# yarn dev
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'dev'
```

**Comment by dvaJi** [comment]
Thanks for reporting it, I'm looking at it.

_Note: And I'm also fixing the process of cloning/building on local machine_
