### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by wingedseahorse** [dvaJi/genshin-builds#17]
Once you put in a value in the todo list that meets or exceeds the required amount you cannot update it with a lower amount (if you made a mistake or end up using those mats elsewhere). After editing, saving and refreshing the page the value will always revert to the zeroed out value (eg 28/28). You would have to remove the character listing altogether and redo the entry to reset it. 

Also, this is pretty minor, but from what I can tell the todo list 'farm today' is based off my local clock but, as an Australian playing on American servers, this showing what domains will be up _tomorrow_. Would be nice to have a dropdown at the bottom of the page or something where I could manually set the region so its consistent. ty

**Comment by dvaJi** [comment]
Hi @wingedseahorse, can you try again? I've added an update that might fix it.

**Comment by wingedseahorse** [comment]
Yes working much better now. Numbers are live updating and don't lock out. :)
