### ISSUE TITLE
[Bug] Ley line sprouts is missing its icon

### ISSUE THREAD

**Issue by ARealDuck** [dvaJi/genshin-builds#7]
Quite literally what it says on the tin

the item "Ley Line Sprout" does not have an icon and instead is just displaying its name
Image of the bug in question is below
[https://puu.sh/IXOsk/8ca4d6fd21.png](url)

how to recreate bug

Simply calculate something that requires Ley Line Sprouts i.e. the skyward blade 70 > 90 and the bug should just show

**Comment by dvaJi** [comment]
Resolved, some icons of materials were missing.
